version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.7.1
    ports:
      - '6333:6333'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:6333/health']
      interval: 10s
      timeout: 5s
      retries: 5
